### ISSUE TITLE
系统找不到指定的路径。: 'tools/gt_t'

### ISSUE THREAD

**Issue by liushuquan2022** [eddy0117/SparseDrive_stream_det#1]
感谢分享！小问题，请方便时回复，谢谢！

运行：
python ./tools/test_my.py projects/configs/sparsedrive_small_stage1_mod.py ckpt/resnet50-19c8e357.pth --deterministic --eval bbox

报错行：
bev_files = sorted(os.listdir('tools/gt_t'), key=lambda x: int(x.split('.')[0]))

信息：
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'tools/gt_t'

**Comment by eddy0117** [comment]
你好, 感謝你的關注, 執行串流偵測的檔案為 tools/streaming_pred.py, 且args是在檔案內進行設定的, 抱歉還沒寫readme造成混淆
